package com.mgm.stocksorting.service.sorting;

import java.util.List;
import java.util.Map;

import com.mgm.stocksorting.domain.ProductDomain;

/**
 * Defines the contract for sorting products based on their computed scores.
 * <p>
 * A {@code SortingStrategy} is responsible for determining the order of products
 * using a score map generated by one or more {@link ScoringRule}s. This allows
 * different sorting behaviors (e.g., ascending, descending, top-N, weighted random)
 * to be implemented independently from the score calculation.
 * </p>
 *
 * @author Miguel Maquieira
 */
public interface SortingStrategy
{
    List<ProductDomain> sort( Map<ProductDomain, Double> scoredProducts, boolean ascending );
}
